[build]
  base = "frontend"
  publish = "."
  command = "echo 'Static site deployment'"

[[redirects]]
  from = "/blog/*"
  to = "/blog/post.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
